version: '3.8'
services:
  postgres:
    image: postgres:15.1
    networks:
      - postgres
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres

    environment:
      POSTGRES_USER: systemadmin
      POSTGRES_PASSWORD: D3v!L1981!Killer00!
      POSTGRES_DB: metacubic
  pgadmin:
    image: dpage/pgadmin4:6.18
    networks:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: support@metacubic.org
      PGADMIN_DEFAULT_PASSWORD: Killer00!D3v!L1981!
  metacore:
    image: dcenttech/metacore:latest
    ports:
      - "3021:3021"
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
