version: "3"
services:
  postgres:
    image: postgres:15.1
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env

  pgadmin:
    image: dpage/pgadmin4:6.18
    networks:
      - postgres
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env

  nestjs-api:
    image: metacore-api
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
